import { categoryData } from "@/data/categoryData";
import Head from "next/head";
import { useStoreState } from "../../../store";
import { useQuery } from "react-query";
import Link from "next/link";
import useProfileCompletionToast from "@/Layout/useProfileCompletionToast";

const JobCategory = () => {
  const { currentUser, getCategories } = useStoreState();
  const { isLoading, data, isError, error } = useQuery("categories", () => {
    return getCategories();
  });
  if (currentUser.role === "jobseeker") useProfileCompletionToast();
  return (
    <>
      <Head>
        <title>Rojgar-Job category</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="pt-8 px-12">
        <h1 className="text-xl font-semibold text-gray-900 mb-6">Categories</h1>
        <ul className="grid grid-cols-2 gap-4 w-full">
          {isLoading ? (
            <h2>Loading...</h2>
          ) : isError ? (
            <h1> {error.message}</h1>
          ) : (
            <>
              {data.map((category, index) => (
                <Link
                  href={`/job/category/${category.name}`}
                  key={category._id}
                  className="cursor-pointer  rounded-md px-4 py-2 bg-white border shadow-sm hover:bg-gray-100"
                >
                  <li>
                    <div className="font-medium">{category.name}</div>
                    <br />
                    <div className="text-xs text-gray-700">
                      {category.job_count} jobs
                    </div>
                  </li>
                </Link>
              ))}
            </>
          )}
        </ul>
      </div>
    </>
  );
};

export default JobCategory;
